[application]
name = "doletc"
version = "2.0.0-beta.2"
entry = "build/pipeline_build.dlt"
type = "console"

[build]
default-target = "windows"
default-profile = "release"
incremental = true
targets = ["windows", "linux"]

[targets.windows]
id = "windows/x86_64"
package-include = ["toolchains/llvm/1/hosts/windows-x86_64"]

[targets.linux]
id = "linux/x86_64"
package-include = ["toolchains/llvm/1/hosts/linux-x86_64"]

[profiles.dev]
optimization = 0
no-console = false

[profiles.release]
optimization = 3
no-console = false

[tools]
doletc = "bin/doletc.exe"

[packages]
auto-sync = false

[hooks]
before-build = ["python scripts/generate_pipeline.py"]

[package]
directory = "dist"
include-assets = false
executable-directory = "bin"
include = ["library", "toolchains/llvm/1/toolchain.toml", "tools", "README.md", "LICENSE"]
